[module]

# Mount Partial
[[module.mounts]]
source = "partials"
target = "layouts/partials/feathericons"

# Feather Icons
[[module.imports]]
path="github.com/feathericons/feather"
[[module.imports.mounts]]
source = "icons"
target = "assets/feathericons"



